In [15]:
!pip install xlrd --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (2.0.1)

In [49]:
import pandas as pd

# 1주차
df1 = pd.read_excel("/content/drive/MyDrive/대학원/202209자료/1)기계학습기초/data/zoom_participants_83169866693.xls")

In [50]:
df1.drop(['참여시작시간','참여종료시간','참여시간','번호'], axis=1, inplace=True)

In [51]:
df1.head()

         학번   이름   역할
0   2020177  김효실  교수자
1  K2021504  유혁문   학생
2  K2021020  노용문   학생
3  K2020510  우윤우   학생
4  K2021027  오지수   학생

In [52]:
# 2주차
df2 = pd.read_excel("/content/drive/MyDrive/대학원/202209자료/1)기계학습기초/data/zoom_participants_86750070616.xls")

In [53]:
df2.drop(['참여시작시간','참여종료시간','참여시간','번호'], axis=1, inplace=True)

In [54]:
df2.head()

         학번   이름   역할
0   2020177  김효실  교수자
1  K2021017  김채현   학생
2  K2021035  홍성규   학생
3  K2021033  조윤정   학생
4  K2021029  이범찬   학생

- 2주 수업을 진행한 줌 참여자료를 이용하여, 출석부에 표기를 합니다.

- 출석시 O를 결석시 X로 표기합니다. 표기된 결과를 "전자출석부 텍스트 출석부_기계학습기초_01분반.xls"에 저장합니다.

In [ ]:
# 출석부
df = pd.read_excel("/content/drive/MyDrive/대학원/202209자료/1)기계학습기초/data/전자출석부 텍스트 출석부_기계학습기초_01분반.xls")

In [83]:
df.dropna(how = 'all', inplace=True)
df.head(2)

    이름      학과        학번  1 주차  2 주차
0  곽승준  인공지능전공  K2021012   NaN   NaN
1  김봉상  인공지능전공  K2021014   NaN   NaN

In [95]:
# df 1주차 넣기
data = pd.merge(df,df1, how='outer',on=['이름','학번'], indicator=True)
data.loc[(data._merge == 'both'),('1 주차')] = 'O'

In [96]:
data.drop(['_merge','역할'],axis=1, inplace=True)
data.head()

    이름      학과        학번 1 주차  2 주차
0  곽승준  인공지능전공  K2021012    O   NaN
1  김봉상  인공지능전공  K2021014    O   NaN
2  김용욱  인공지능전공  K2021015    O   NaN
3  김채현  인공지능전공  K2021017    O   NaN
4  김형준  인공지능전공  K2021018    O   NaN

In [100]:
data1 = pd.merge(data, df2, how='outer',on=['이름','학번'], indicator=True)
data1.loc[(data1._merge == 'both'),('2 주차')] = 'O'
data1.drop(['_merge','역할'],axis=1, inplace=True)
data1.dropna(inplace=True)
data1

     이름         학과        학번 1 주차 2 주차
0   곽승준     인공지능전공  K2021012    O    O
1   김봉상     인공지능전공  K2021014    O    O
2   김용욱     인공지능전공  K2021015    O    O
3   김채현     인공지능전공  K2021017    O    O
4   김형준     인공지능전공  K2021018    O    O
5   남용휘     인공지능전공  K2021019    O    O
6   노용문     인공지능전공  K2021020    O    O
7   박준호     인공지능전공  K2021501    O    O
8   성희정     인공지능전공  K2021502    O    O
9   신용주     인공지능전공  K2021022    O    O
10  안혜영     인공지능전공  K2021024    O    O
11  안혜영     인공지능전공  K2021024    O    O
12  오동규     인공지능전공  K2021503    O    O
13  오지수     인공지능전공  K2021027    O    O
14  우윤우     인공지능전공  K2020510    O    O
15  유혁문     인공지능전공  K2021504    O    O
16  윤영선     인공지능전공  K2020511    O    O
17  이문용     인공지능전공  K2021505    O    O
18  이범찬     인공지능전공  K2021029    O    O
19  이해수     인공지능전공  K2021506    O    O
20  이효중     인공지능전공  K2021030    O    O
21  임준혁     인공지능전공  K2021031    O    O
22  임항빈     인공지능전공  K2021032    O    O
23  정민욱     인공지능전공  K2021507    O    O
24  조애자  소프트웨어교육전공  K2020506    O    O
25  조윤정     인공지능전공  K2021033    O    O
26  최원호     인공지능전공  K2020514    O    O
27  홍성규     인공지능전공  K2021035    O    O

In [105]:
data1.to_excel('/content/drive/MyDrive/대학원/202209자료/1)기계학습기초/과제/전자출석부 텍스트 출석부_기계학습기초_01분반.xls', engine='openpyxl')